#for clock
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

#for jointstatepublisher Plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS


#for odometery DiffDrive Plugin
- ros_topic_name: "odom"
  gz_topic_name: "odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

#for tf DiffDrive Plugin
- ros_topic_name: "tf"
  gz_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS

#for cmd_vel DiffDrive Plugin
- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

#for ultrasonic
- ros_topic_name: "ultrasonic_sensor"
  gz_topic_name: "ultrasonic_sensor"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL

#for jointstatepublisher Plugin for stepper motor
#- ros_topic_name: "stepper_joint_states"
#  gz_topic_name: "stepper_joint_states"
#  ros_type_name: "sensor_msgs/msg/JointState"
#  gz_type_name: "gz.msgs.Model"
#  direction: GZ_TO_ROS